# What server(s) to connect to, and credentials/channels to join by default.
servers:
  irc.foonetic.net:
    port: 6667
    nick: Kitn
    name: Aaeriele
    channels:
      - '#kitntest'
    modes: '+B'
    auth:
      to: NickServ
      msg: 'identify <password>'

sigil: '.'

database:
  path: 'kitn.sqlite3'

urlannounce:
  - '#kitntest'

bing:
  appid: '123B123C1231239F123A123123ECC123123'

google:
  apikey: 'AD2923NF3123_E123asdLL9845M45MKK'
