# What server(s) to connect to, and credentials/channels to join by default.
servers:
  irc.freenode.net:
    port: 6667
    nick: CorpCat
    name: "Maintained by you"
    corps:
      corp1:
        channel: '##corp1'
        action: 'voice'
        allowed:
          - 'My Corp'
      alliance1:
        channel: '##alliance1'
        action: 'kick'
        allowed:
          - 'Member Corp 1'
          - 'Member Corp 2'
          - 'Member Corp 3'
    auth:
      to: NickServ
      msg: 'identify sekrit'

sigil: '!'

database:
  path: 'corpcat.sqlite3'

admin:
  - 'admin!user@example.com'
